name: PEP8 Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pep8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install flake8
    - name: Lint with flake8
      run: |
        ls
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=15 --max-line-length=120 --statistics